---
defaultGroups:
  - sudo
  - audio
  - video
  - cdrom
  - dip
  - plugdev
  - netdev
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: true
passwordRequirements:
    nonempty: true
userShell: /bin/bash
