#!/bin/sh
set -e

lb config noauto \
    --apt-indices false \
    --apt-recommends false \
    --apt-secure false \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --bootappend-live "boot=live components username=darbs hostname=darbs" \
    --bootloaders grub-efi \
    --checksums sha256 \
    --debian-installer none \
    --debootstrap-options "--keyring=/usr/share/keyrings/kali-archive-keyring.gpg" \
    --distribution kali-rolling \
    --image-name "darbs" \
    --iso-application "darbs" \
    --iso-publisher "darbs" \
    --iso-volume "darbs" \
    --mirror-bootstrap http://http.kali.org/kali \
    --mirror-chroot http://http.kali.org/kali \
    --security false \
    --updates false \
    --source false \
    "${@}"
